workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH

image: python:3.12.6

stages:
  - build
  - test


before_script:
  - pip install -r requirements-dev.txt

unittest:
  stage: test
  script:
    - pytest tests

mypy:
  stage: test
  script:
    - mypy ./src
    - mypy main.py

black:
  stage: test
  script:
    - black --diff --check ./src
    - black --diff --check main.py

isort:
  stage: test
  script:
    - isort --check-only --diff --profile black ./src
    - isort --check-only --diff --profile black main.py