services:
  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - .env:/app/.env
      - ./media:/app/media
      - ./logs:/app/logs
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    networks:
      - app_network
    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./media:/app/media
    networks:
      - app_network
    depends_on:
      - app


networks:
  app_network:
    driver: bridge