name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Run unittests
        run: pytest tests --cov

      - name: Run mypy
        run: |
          mypy ./src
          mypy main.py

      - name: Run black
        run: |
          black --diff --check ./src
          black --diff --check main.py

      - name: Run isort
        run: |
          isort --check-only --diff --profile black ./src
          isort --check-only --diff --profile black main.py